version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: b7mailer-app
        container_name: b7mailer-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: b7mailer-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: b7mailer
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: b7mailer-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_USER: laravel
            PMA_PASSWORD: laravel
        ports:
            - "8080:80"
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: b7mailer-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html:ro,cached
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    db_data:
